### ISSUE TITLE
AzureRMR's set_tags() not working properly when called inside function

### ISSUE THREAD

**Issue by kelnerrr** [Azure/AzureRMR#18]
Hello,

I have quite a strange problem with the *set_tags()* method from the AzureRMR package.
I posted the question on SO ([link](https://stackoverflow.com/questions/66051425/azurermr-object-not-found-when-set-tag-inside-a-function)).

In nutshell – *set_tags()* works fine in a script but fails while run inside a function (it cannot find an object passed to my function). The other methods (e.g. *get_resource()*) work ok within a function.

`    az$`
`      get_subscription(resource$subscriptionid)$`
`      get_resource_group(resource$resourcegroup)$`
`      get_resource(type = resource$type, name = resource$name)$`
`      set_tags(MYTAG = resource$new_tag)`

Is it a bug? Should I do it differently while in a function?

Best regards,
Piotr

**Comment by hongooi73** [comment]
This is because `set_tags` uses `match.call` to get the unevaluated tagnames. When you pass it an expression, that expression has to be evaluated to get the actual tag. This runs into problems inside `set_tags` due to having to juggle parent frames.

A workaround is to use `eval(substitute(*))` to force the expression to be evaluated:

```r
set_my_tag2 <- function(resources_to_tag)
{
    for(i in seq_len(nrow(resources_to_tag)))
    {
        resource <- resources_to_tag[i, ]
        tag <- resource$newtag
        obj <- az$
            get_subscription(resource$subscriptionid)$
            get_resource_group(resource$resourcegroup)$
            get_resource(type = resource$type, name = resource$name)
        eval(substitute(obj$set_tags(my_tag=.value), list(.value=resource$new_tag)))
    }
}
```

I'll fix this up for the next AzureRMR release.

**Comment by hongooi73** [comment]
In hindsight, it would have been better to avoid all this NSE business and just turn unnamed tag values into tagnames....

**Comment by hongooi73** [comment]
3b5523c2bc81f3d0426ca80adbe5377b05252d01

**Comment by kelnerrr** [comment]
Thanks, Hong! Works OK : )
