### ISSUE TITLE
sign in with a personal account?

### ISSUE THREAD

**Issue by Jiefei-Wang** [Azure/AzureRMR#20]
Hello,

Thanks for making this great package! I'm a newbie in Azure so this might be a silly question. I try to log in using `AzureRMR::create_azure_login()`. It uses the web-based authenticate and asks me to go to the web page 

https://microsoft.com/devicelogin

I follow the instructions showing on my console, but when I type in my account on the web it gives me this error: `You can't sign in here with a personal account. Use your work or school account instead.`, which is kind of surprising as I have used the same process for authenticating Azure CLI. 

I think there might be some options that I need to adjust, but I just cannot figure out them from the function document. I'll appreciate it if you can shed some light on the problem. Any instruction and link will be helpful. Thanks!

Best,
Jiefei

**Comment by hongooi73** [comment]
What is the specific command you used to create the login?

You may need to specify your tenant explicitly:

```
create_azure_login(tenant="yourtenant")
```

**Comment by Jiefei-Wang** [comment]
Thanks for your reply! specifying tenant works for me! I think that's the trick to use a personal account. It might be better to have this in the document.

If this is unexpected behavior, here is my console output that might be helpful for debugging it
```
## This will require a school or work account
az <- AzureRMR::create_azure_login()
httpuv not installed, defaulting to device code authentication
Using device_code flow
Creating Azure Resource Manager login for default tenant
httpuv not installed, defaulting to device code authentication
Using device_code flow
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code S48ARBL5M to authenticate. 
Waiting for device code in browser...
Press Esc/Ctrl + C to abort
```

I'm using Windows 10 and R 4.1. Every package is up-to-date.

Best,
Jiefei

**Comment by hongooi73** [comment]
Auth vignette created in a9837faafd80e9e13d910278d3e3c3a288d99a15
