### ISSUE TITLE
Need Advice: Create Azure Batch Pool from R

### ISSUE THREAD

**Issue by abfleishman** [Azure/AzureRMR#22]
I am hoping to use `AzureRMR` to create a `pool` for an existing `Azure Batch` account.  I have googled and didn't find much help.  I have only used AzureRMR a little bit, but tried the code below and got stuck.  I would appreciate any advice on how to move forward.  Is there another package I should be using?

```
library(AzureRMR)

 AzureRMR::create_azure_login(tenant = creds$password[creds$application == "azure_tenent_id"])
 az <- AzureRMR::get_azure_login(creds$password[creds$application == "azure_tenent_id"])

sub1 <- az$get_subscription(creds$password[creds$application == "azure_subscription_id"])
rg<-sub1$get_resource_group("gpubatch")
a<-rg$get_resource(type = "Microsoft.Batch/batchAccounts",name = "cmigpu")


a$create_subresource(type = "pools",name = "test_pool_1",location="westus2")
```

> Error in process_response(res, match.arg(http_status_handler)) : 
> Bad Request (HTTP 400). Failed to complete operation. Message:
> InvalidRequestBody
> The specified Request Body is not syntactically valid. RequestId:de5ce3e7-2c70-4a17-9c4c-486ef9a95d6f
> Time:2021-09-28T18:17:23.9594212Z
> BatchAccount
> Reason
> Could not find member 'location' on object of type 'Pool'. Path 'location', line 1, position 12.
> PropertyPath
> location.

**Comment by hongooi73** [comment]
Hi, I'm not familiar with the batch service. However, it looks like you need to supply the various properties as given here: https://docs.microsoft.com/en-us/rest/api/batchmanagement/pool/create

See in particular the example request on that page. The JSON in the request would look a bit like this, translated into R:

```r
a$create_subresource(...,
  properties=list(
    vmSize="xxx",
    deploymentConfiguration=list(
      virtualMachineConfiguration=list(
        imageReference=list(
          id="xxxxxxx"
        ),
        nodeAgentSkuId="batch.node.ubuntu 18.04"
      )
    )
  )
)
```

**Comment by hongooi73** [comment]
Closing, let me know if you still have problems
