### ISSUE TITLE
list_resources() from AzureRMR fails for some subscriptions with “Invalid object names” error

### ISSUE THREAD

**Issue by kelnerrr** [Azure/AzureRMR#8]
I'm trying to list all the resources in a subscription.
Unfortunately, it fails with the following error:

    library(AzureRMR)

    az <- get_azure_login()
    #> Loading Azure Resource Manager login for default tenant
    az$
      get_subscription('00000000-0000-0000-0000-000000000000')$
      list_resources()
    #> Error in validate_object_names(names(parms), required_names, optional_names): Invalid object names

<sup>Created on 2020-05-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I tried it for another subscription and it works fine.

**Comment by Hong-Revo** [comment]
Interesting, are you able to retrieve the resources at the resource group level? How many resources do you have in the sub?

You can run the following to see which resources have unexpected fields present. Post the result here.

```
sub <- get_azure_login()$get_subscription("xxx-xxx")
reslist <- sub$do_operation("resources")$value
lapply(reslist, names)
```

**Comment by kelnerrr** [comment]
I tried

``` r
sub$get_resource_group('x-xxx-xxxxxxx')$list_resources()
```
and it works for this random resource group. I suppose it may fail for some other.

I have ~2500 resources in that subscription (checked on Azure Portal).

Running your code gives me the results for the first 1000 resources. The output's excerpt:

``` r
'id' 'name' 'type' 'location' 'tags'  # most of them
'id' 'name' 'type' 'location'
'id' 'name' 'type' 'sku' 'location' 'tags'
'id' 'name' 'type' 'sku' 'managedBy' 'location' 'zones' 'tags'
'id' 'name' 'type' 'location' 'zones' 'plan' 'tags'
'id' 'name' 'type' 'sku' 'kind' 'location' 'tags'
```

**Comment by Hong-Revo** [comment]
Thanks! That `zone` field is the problem. I'll fix the package.

Out of interest, can you tell me what type of resource it is?

**Comment by Hong-Revo** [comment]
The following code should let you pick out the resources that are causing problems.

```r
allowed_names <- c("id", "name", "type", "identity", "kind", "location", "managedBy", "plan",
    "properties", "sku", "tags", "etag")
reslist <- get_paged_list(sub$do_operation("resources"), sub$token)
good <- sapply(reslist, function(res) all(names(res) %in% allowed_names))

reslist[!good]

sapply(reslist[!good], "$", type)
```

**Comment by kelnerrr** [comment]
They are all Disks and Virtual Machines.

The last line (`sapply(reslist[!good], "$", type)`) gave me only nulls but I checked the output of `reslist[!good]`.

**Comment by Hong-Revo** [comment]
Thanks. That last line should actually be `sapply(reslist[!good], "[[", "type")`

**Comment by Hong-Revo** [comment]
I've pushed some changes in the resource-fix branch. Let me know if this fails to fix the problem.

**Comment by kelnerrr** [comment]
Thanks, Hong. I just checked and the error is no more : )
